name: BTC Daily Training + Dashboard

on:
  schedule:
    - cron: "0 0 * * *"   # run daily at 00:00 UTC
  workflow_dispatch:      # allow manual run

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas yfinance ta xgboost joblib plotly

      - name: Run training & prediction
        run: |
          python train_and_predict.py

      - name: Build dashboard
        run: |
          python dashboard.py

      - name: Commit artifacts
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add btc_dataset.csv btc_xgb_5day_model_latest.joblib btc_predictions.csv btc_dashboard.html
          git commit -m "Daily BTC update: $(date -u +'%Y-%m-%d')" || echo "No changes to commit"
          git push

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          keep_files: true
          enable_jekyll: false
